version: "3.3"

services:
  db:
    container_name: api_authors_db
    image: bitnami/postgresql:latest
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_authors
    volumes:
      - db_data:/bitnami/postgresql

  storage:
    container_name: api_authors_storage
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Admin123456
    volumes:
      - storage_data:/bitnami/minio/data

volumes:
  db_data:
  storage_data:
