version: "3.3"

services:
  db:
    container_name: api_authors_db
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=api_authors
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
