name: API Authors Application

on:
  push:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_DB: api_authors
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build and test project
        run: ./mvnw clean install

      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build --build-arg DB_URL=jdbc:postgresql://postgres/api_authors --build-arg DB_USER=admin --build-arg DB_PASS=admin -t thiagords042/api_authors_spring:latest .

      - name: Publish image
        run: docker push thiagords042/api_authors_spring
